version: '3.9'

services:
    # backend:
    #     build:
    #       context: .
    #       dockerfile: ./Dockerfile
    #     env_file: .env
    #     environment:
    #         RDS_HOST: "db"
    #     ports:
    #         - "3000:3001"

    db:
        image: postgres:16-alpine
        restart: always
        environment:
          - POSTGRES_DB=main
          - POSTGRES_HOST=localhost
          - POSTGRES_PORT=5432
          - POSTGRES_USERNAME=postgres
          - POSTGRES_PASSWORD=postgres
        ports:
          - "5432:5432"
        volumes:
          - db:/var/lib/postgresql/data
volumes:
      db:
